trigger:
- main

pool:
  name: Default  # Your self-hosted agent pool name
  # demands are optional; you can filter agents by OS if needed
  # demands:
  #   - agent.os -equals Linux

variables:
  phpVersion: 8.1

steps:
# Step 1: Install PHP on your machine if not installed
- script: |
    sudo apt-get update
    sudo apt-get install -y php8.1 php8.1-cli php8.1-mbstring php8.1-xml unzip
    php -v
  displayName: 'Install PHP 8.1'

# Step 2: Install Composer if not installed
- script: |
    curl -sS https://getcomposer.org/installer | php
    sudo mv composer.phar /usr/local/bin/composer
    composer --version
  displayName: 'Install Composer'

# Step 3: Install dependencies
- script: composer install --no-interaction --prefer-dist
  displayName: 'Composer Install'

# Optional Step 4: Run tests if you have PHPUnit
# - script: vendor/bin/phpunit
#   displayName: 'Run PHPUnit Tests'
